project:
  type: book

book:
  title: "Manual of Tau-Argus"
  author: ""
  date: "9/3/2023"
  chapters:
    - index.qmd
    - 02_Introduction.qmd
    - 03_Producing_Safe_tables.qmd
    - 04_A_tour_of_Ï„-ARGUS.qmd
    - 05_Reference_Section_-_Description_of_the_Menu_Items.qmd
    - 06_Further_descriptions.qmd
    - 07_Index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

execute:
  freeze: auto



