project:
  type: book

book:
  title: "Manual of Tau-Argus"
  author: ""
  date: "9/3/2023"
  chapters:
    - index.qmd
    - 01_Introduction.qmd
    - 02_Producing_Safe_tables.qmd
    - 03_A_tour_of_tauargus.qmd
    - 04_Reference_Section_-_Description_of_the_Menu_Items.qmd
    - 05_Further_descriptions.qmd
    - 06_Index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - custom.scss

execute:
  freeze: auto



