## Information loss in terms of cell costs^[^8]^
In case of secondary cell suppression it is possible that a dataprotector might want to differentiate between the candidate cells forsecondary suppression. It is possible that they would strongly preferto preserve the content of certain cells, and are willing to sacrificethe values of other cells instead. A mechanism that can be used tomake such a distinction between cells in a table is that of cellcosts. In τ-argus it is possible to associate different costs with thecells in a table. The higher the cost the more important thecorresponding cell value is considered and the less likely it will besuppressed. We shall interpret this by saying that the cells with thehigher associated costs have a higher information content. The aim ofsecondary cell suppression can be summarised by saying that a safetable should be produced from an unsafe one, by minimising theinformation loss, expressed as the sum of the costs associated withthe cells that have secondarily been suppressed.
τ-argus offers several ways to compute these costs. The first optionis to compute the costs as the sum of the contributions to a cell.Alternatively another variable in the data file can be used as thecost function. Secondly this cost can be the frequency of thecontributors to a cell, and finally each cell can have cost = 1,minimising the number of suppressed cells.

