## Sensitive cells in magnitude tables^[^5]^
The well-known dominance rule is often used to find the sensitivecells in tables, i.e. the cells that cannot be published as they mightreveal information on individual respondents. More particularly, thisrule states that a cell of a table is unsafe for publication if a few(*n*) major (largest) contributors to a cell are responsible for acertain percentage (*k*) of the total of that cell. The idea behindthis rule is that in that case at least the major contributorsthemselves can determine with sufficient precision the contributionsof the other contributors to that cell. The choice *n*=3 and *k*=70%is not uncommon, but τ-argus will allow the users to specify their ownvalues of *n* and *k*.
As an alternative the prior-posterior rule has been proposed. Thebasic idea is that a contributor to a cell has a better chance toestimate competitors in a cell than an outsider, and also that thesekind of intrusions can occur rather often. The precision with which acompetitor can estimate is a measure of the sensitivity of a cell. Theworst case is that the second largest contributor will be able toestimate the largest contributor. If this precision is more than *p*%,the cell is considered unsafe. An extension is that also the globalknowledge about each cell is taken into account. In that case weassume that each intruder has a basic knowledge of the value of eachcontributor of *q*%. Note, that it is actually the ratio p/q thatdetermines which cells are considered safe, or unsafe. In this versionof τ-argus, the q‑parameter is fixed to 100. Literature refers to thisrule as (minimum protection of) p%‑rule. If the intention is to statea prior-posterior rule with parameters p~0~ and q~0~, whereq~0~~ ~\<~ ~100, choose the parameter p of the p%‑ruleas p = p~0~/q~0~\*100. See Loeve (2001)^[^6]^
With these rules as a starting point it is easy to identify thesensitive cells, provided that the tabulation package has the facilitynot only to calculate the cell totals, but also to calculate thenumber of contributors and the n individual contributions of the majorcontributors. Tabulation packages like ABACUS (from StatisticsNetherlands) and the package 'SuperCross' developed in Australia bySpace-Time Research have that capacity. In fact τ-argus not onlystores the sum of the n major contributions for each cell, but theindividual major contributions themselves. The reason for this is thatthis is very handy in case rows and columns etc. in a table arecombined. By merging and sorting the sets of individual contributionsof the cells to be combined, one can quickly determine the majorcontributions of the new cell, without going back to the originalfile. This implies that one can quickly apply the dominance rule orthe p%-rule to the combined cells. Combining rows and columns (tableredesign) is one of the major tools for reducing the number of unsafecells.
This too is the reason why τ-argus can read microdata files and buildthe tables itself. However due to continuous demands from users wehave now also provide the option to read ready-made tables, but withthe restriction that the options for table redesign will not beavailable in that case.
A problem, however, arises when also the marginals of the table arepublished. It is no longer enough to just suppress the sensitivecells, as they can be easily recalculated using the marginals. Even ifit is not possible to exactly recalculate the suppressed cell, it ispossible to calculate an interval that contains the suppressed cell.This is possible if some constraints are known to hold for the cellvalues in a table. A commonly found constraint is that the cell valuesare all nonnegative.
If the size of such an interval is rather small, then the suppressedcell can be estimated rather precisely. This is not acceptable either.Therefore it is necessary to suppress additional information toachieve sufficiently large intervals.
Several solutions are available to protect the information of thesensitive cells:

-   Combining categories of the spanning variables (table redesign).
    > Larger cells tend to protect the information about the individual
    > contributors better.

-   Suppression of additional (secondary) cells to prevent the
    > recalculation of the sensitive (primary) cells.
The calculation of the optimal set (with respect to the loss ofinformation) of secondary cells is a complex OR-problem. τ-argus hasbeen built around this solution, and takes care of the whole process.A typical τ-argus session will be one in which the users will first bepresented with the table containing only the primary unsafe cells. Theuser can then choose how to protect these cells. This can involve thecombining of categories, equivalent to the global recoding of μ-argus.The result will be an update of the table with fewer unsafe cells(certainly not more) if the recoding has worked. At a certain stagethe user requests the system to solve the remaining unsafe cells byfinding secondary cells to protect the primary cells.
At this stage the user can choose between several options to protectthe primary sensitive cells. Either they choose the hypercube methodor the optimal solution. In this case they also has to select thesolver to be used, Xpress or cplex or the free solver soplex. Afterthis, the table can be stored for further processing if necessary, andeventual publication.

