## Controlled rounding^[^13]^
Controlled rounding is a rounding procedure that, differently fromother rounding methods, yields additive rounded tables. That is to saythat the rounded values add up to the rounded totals and sub-totalsshown in the table. This property not only permits the release ofrealistic tables but also makes it impossible to reduce the protectionby "unpicking" the original values by exploiting the differences inthe sums of the rounded values. The Controlled Rounding Procedure(CRP) implemented in τ-argus also allows the specificationhierarchical tables.
Controlled rounding is a SDC method that is most effective forfrequency tables. In fact, this method gives adequate protection tosmall frequencies by creating uncertainty also with respect to zerovalues (*i.e.* empty cells). The same cannot be said for suppressionin the way it is implemented now in τ-argus.
Restricted and non-restricted controlled rounding
In Zero-restricted Controlled Rounding the rounded values are chosenleaving unaltered the original values that are already multiples ofthe rounding base, while rounding the others to one of the adjacentmultiples of this base. The modified values are chosen so that the sumof the absolute differences between the original values and therounded ones is minimized under the additivity constraint. Therefore,some values will be rounded up or down to the most distant multiple ofthe base in order to satisfy the constraints. In most cases such asolution can be found but in some cases it cannot. Thezero-restriction constraint in CRP can be relaxed allowing the valuesto be rounded to a nonadjacent multiple of the base. This relaxationis controlled by allowing a maximum number of *steps*. For example,consider rounding the value 7 when the base equals 5. Inzero-restricted rounding, the solution can be either 5 or 10. If 1step is allowed, the solution can be 0, 5, 10 or 15. In general, let*z* be the integer to be rounded in base *b*, then this number can bewritten as
$${z = {\mathit{ub} + r}},$$
where *ub* is the lower adjacent multiple of *b* (hence *u* is thefloor value of *z/b*) and *r* is the remainder. In the zero-restrictedsolution the rounded value, *a*, can take values:
$$\left\{ \begin{matrix}{{a = \mathit{ub}}\mathit{if}{r = 0};} \\{{a = \left\{ \begin{matrix}\mathit{ub} \\{{({u + 1})}b}\end{matrix} \right.}\mathit{if}{r \neq 0.}}\end{matrix} \right.$$
If *K* steps are allowed, then *a*, can take values:
$$\left\{ \begin{matrix}{{a = \mathit{\max}}{\{{0,{({u + j})}}\}}b,{j = {- K}},\ldots,K,\mathit{if}{r = 0};} \\{{a = \mathit{\max}}{\{{o,{({u + j})}}\}}b,{j = {- K}},\ldots,{({K + 1})},\mathit{if}{r \neq 0.}}\end{matrix} \right.$$
Optimal, first feasible and RAPID solutions^**[^14]**^
For a given table there could exist more than one controlled roundedsolutions; any of these solutions is a *feasible* solution. TheControlled Rounding Program embedded in τ-argus determines the*optimal* solution by minimising the sum of the absolute distances ofthe rounded values from the original ones. Denoting the cell values,including the totals and sub-totals, with *z*~i~ and the correspondingrounded values with *a*~i~, the function that is minimised is
$${\sum\limits_{i = 1}^{N}{\mid {z_{i} - a_{i}} \mid}},$$
where *N* is the number of cells in a table (including the marginalones). The optimisation procedure for controlled rounding is a rathercomplex one (*NP*-complete program), so finding the optimal solutionmay take a long time for large tables. In fact, the algorithmiteratively builds different rounded tables until it finds the optimalsolution. In order to limit the time required to obtain a solution,the algorithm can be stopped when the first feasible solution isfound. In many cases, this solution is quite close to the optimal oneand it can be found in significantly less time.
The RAPID solution is produced by CRP as an approximated solution whennot even a feasible one can be found. This solution is obtained byrounding the internal cells to the closest multiple of the base andthen computing the marginal cells by addition. This means that thecomputed marginal values can be many jumps away from the originalvalue. However, a RAPID solution is produced at each iteration of thesearch for an optimal one and it will improve (in terms of the lossfunction) over time. τ-argus allows to stop CRP after the first RAPIDis produced, but this solution is likely to be very far away from theoptimal one.
Protection provided by controlled rounding
The protection provided by controlled rounding can be assessed byconsidering the uncertainty about the disclosive true values achievedreleasing rounded values; that is the existence interval that anintruder can compute for the rounded value. We assume that also thevalues of the rounding base, *b*, and the number of steps allowed,*K*, are released together with the rounded table. Furthermore, weassume that it is known that the original values are frequencies(hence nonnegative integers).
**Zero-restricted rounding**
Given a rounded value, *a*, an intruder can compute the followingexistence intervals for the true value, *z*:
$$\begin{matrix}{{z \in {\lbrack{0,{b - 1}}\rbrack}}\mathit{if}{a = 0}} \\{{z \in {\lbrack{{{a - b} + 1,}{{a + b} - 1}}\rbrack}}\mathit{if}{a \neq 0.}}\end{matrix}$$
For example, if the rounding base is *b*=5 and the rounded value is*a*=0, a user can determine that the original value is between 0 and4. If the rounded value is not 0, then users can determine that thetrue value is between plus or minus 4 units from the published value.
****K-step rounding****
As mentioned before, it is assumed that the number of steps allowed isreleased together with the rounded table. Let *K* be the number ofsteps allowed, then an intruder can compute the following existenceintervals for the true value *z*:
$$\begin{matrix}{{z \in {\lbrack{0,{({K + 1})}{b - 1}}\rbrack}}\mathit{if}{a < {({K + 1})}}b} \\{{z \in {\lbrack{{a - {({K + 1})}}{b + 1,}{a + {({K + 1})}}{b - 1}}\rbrack}}\mathit{if}{a \geq {({K + 1})}}\mathit{b.}}\end{matrix}$$
For example, assume that for controlled rounding with *b*=5 and *K*=1,*a*=15, then a user can determinethat$${z \in {\lbrack{6,24}\rbrack}}.$$
Choosing the parameters for Controlled Rounding
The parameters that can be chosen for rounding are the rounding base,*b*, and the number of steps allowed. If their value is released,users (including potential intruders) will be able to computeexistence intervals for the true values according to the formulaegiven above. Then, the choice of the parameters' values depends on theprotection required for the disclosive values. Of course, the largerthe existence interval the greater the protection but also the*damage* caused to the data. The choice of the rounding base, then,should be made by the data protector considering the protectionrequirements and the damage caused to the data. A discussion on howexistence intervals can be related to protection requirements can befound, for example, in Willenborg and de Waal (2001). Below we givesome general considerations on the effect of different choices of therounding base.
Frequencies are disclosive if their values are not larger than achosen threshold, say *f*. In τ-argus the minimal rounding base is*b*=*f*. When this value is chosen, disclosive values can be roundedeither to 0 or to *b*. Hence, an intruder would know that allpublished zeros are disclosive values, while he or she could notdetermine if a published value equal to *b* is a disclosive value or alarger, safe, one. In some cases this protection can be consideredinsufficient because it is required that the existence interval forvalues rounded to zero contains at least one safe value. Then thevalue of *b* must be chosen to be greater than *f* or the number ofsteps allowed must be greater than zero. It must be stressed, however,that the larger the base and the greater the damage inflicted to thedata (including safe values). In some cases, data protector may behappy with a base that is less than the minimum frequency threshold.For example, it could be decided that the width of the existenceinterval must be not less than the minimum frequency. In this case,the base should be chosen to be the minimal integer not smallerthan{.image .placeholderoriginal-image-src="./ObjectReplacements/Object 10"original-image-title="" width="0.762cm" height="0.524cm"}. Using asmaller base than the minimum safe frequency can be achieved inτ-argus by lowering the threshold before computing the table. This"trick" is allowed in rounding because the procedure does not changeif the disclosive cells are changed (unlike secondary suppression).

