## Table redesign
If a large number of sensitive cells are present in a table, it mightbe an indication that the spanning variables are too detailed. In thatcase one could consider combining certain rows and columns in thetable. (This might not always be possible because of publicationpolicy.) Otherwise the number of secondary cell suppressions mightjust be too enormous. The situation is comparable to the case ofmicrodata containing many unsafe combinations. Rather than eliminatingthem with local suppressions one can remove them by using globalrecodings. For tabular data we use the phrase "table redesign" todenote an operation analogous to global recoding in microdata sets.The idea of table redesign is to combine rows, columns etc., by addingthe cell contents of corresponding cells from the different rows,columns etc. It is a property of the sensitivity rules that a jointcell is safer than any of the individual cells. So as a result of thisoperation the number of unsafe cells is reduced. One can try toeliminate all unsafe combinations in this way, but that might lead toan unacceptably high information loss. Instead, one could stop at somepoint, and eliminate the remaining unsafe combinations by using othertechniques such as cell suppression.

