## Sensitive cells in frequency count tables
In the simplest way of using τ-argus, sensitive cells in frequencycount tables are defined as those cells that contain a frequency thatis below a certain threshold value. This threshold value is to beprovided by the data protector. This way of identifying unsafe cellsin a table is the one that is implemented in the current version ofτ-argus It should be remarked, however, that this is not always anadequate way to protect a frequency count table.[^7] Yet it is applieda lot. Applying a dominance rule or a p% rule is useless in thiscontext. One should think about possible disclosure risks that afrequency count table poses and possible disclosure scenarios in orderto simulate the behaviour of an intruder. Such an analysis wouldprobably come up with different insights than using a simplethresholding rule, *e.g.* like the one sketched in the reference justmentioned. We just mention here the risks of group-disclosure; when a(small) group of respondents have all the same score on a certaincategory. This risk is often also referred to as the problem of100%-cells. Further research on this topic is being carried out ata.o. Statistics Netherlands.

