## The modular approach for linked tables
When tables are linked through simple linear constraints, cellsuppressions must obviously be coordinated between tables. The mosttypical case is when tables share common cells (usually marginals),i.e., when they are linked through constraints saying literally thatcell *X* of table A is identical to cell *Y* of table B.
Suppose a set of *N* tables, {*T*~1~,...,*T*~*N*~}, need to beprotected. These tables are assumed to be linked. Each table has ahierarchical structure that may differ from the hierarchicalstructures of the other tables. However, it is assumed that tablesusing the same spanning variables have hierarchies that can becovered. Loosely speaking this means that a single hierarchy can beconstructed such that all hierarchies of the same variable in the *N*tables are a sub hierarchy of the cover hierarchy. See De Wolf andGiessing (2009) for more details. In the context of pre-planned tableproduction processes which are typically in place in statisticalagencies for the production of certain sets of pre-specified standardtabulations, it is normally no problem to satisfy these conditions.Literally speaking, the assumption is that tables in a set of linkedtables may present the data in a breakdown by the same spanningvariable at various amounts of detail. But only under the conditionthat, if in one of the tables some categories of a spanning variableare grouped into a certain intermediate sum category, during SDCprocessing this intermediate sum category is considered in any othertable presenting the data in a breakdown of the same spanning variableand at that much detail.
The idea is then as follows. Suppose that the *N* tables{*T*~1~,...,*T*~*N*~} that need to be protected simultaneously,contain *M* different spanning variables. Since the hierarchies aresupposed to be coverable, an *M*-dimensional table exists having allthe specified tables as subtables. The spanning variables will benumbered 1 up to *M*.
Each spanning variable can have several hierarchies in the specifiedtables. Denote those hierarchies for spanning variable *i* by[]{.image .placeholderoriginal-image-src="./ObjectReplacements/Object 1"original-image-title="" width=1.54cm height="0.658cm} where*I*~*i*~ is the number of different hierarchies of variable *i*.
Define the *M*-dimensional table by the table with spanning variablesaccording to hierarchies *G*~1~,...,G~*M*~ such that, for each *i* =1,\..., *M* hierarchy *G*~*i*~ covers the set of hierarchies{[]{.image .placeholderoriginal-image-src="./ObjectReplacements/Object 2"original-image-title="" width=0.524cm height="0.658cm}} with *j* =1,..., *I*~*i*~. This *M*-dimensional table will be called the covertable. See De Wolf and Giessing (2009) for more details.
Then use the Modular approach (see section [2.10]) on thecover table *T*~*C*~, but only consider those subtables that are alsosubtables of at least one of the specified tables *T*~1~,...,*T*~*N*~and disregard the other subtables.
I.e., the procedure of the Modular approach is followed, but duringthat process any simple subtable that is not a subtable of any of thetables in the set {*T*~1~,...,*T*~*N*~} is skipped. I.e., the orderthe simple subtables will be protected, is the same as in the'complete' Modular approach, only some subtables will be skipped.
See De Wolf and Hundepool (2010) for a practical application of theAdjusted Modular Approach.
References on the modular approach for linked tables
De Wolf, P.P. and S. Giessing (2009), Adjusting the τ-argus modularapproach to deal with linked tables, Data & Knowledge Engineering,Volume 68, Issue 11, pp. 1160-1174.
De Wolf, P.P. and A. Hundepool (2010), Three ways to deal with a setof linked SBS tables using τ-argus, Privacy in Statistical Databases,J. Domingo-Ferrer and E. Magkos (Eds.), Springer 2010, LNCS 6344 pp.66-74.

