## Network solution for large 2 dimensional tables with one hierarchy

$\tau$-Argus also contains a solution for the secondary cell suppression based on network flows. This contribution is by Jordi Casto of the Universitat Politècnica de Catalunya in Barcelona. The network flows solution for cell suppression implements a fast heuristic for the protection of statistical data in two-dimensional tables with one hierarchical dimension (1H2D tables). This new heuristic sensibly combines and improves ideas of previous approaches for the secondary cell suppression problem in two-dimensional general, see Castro(1994)and positive tables, see Kelly(1992) and Castro(2003) tables. Details about the heuristic can be found in Castro(1996) and Cox(1995).Unfortunately this approach is only possible for two-dimensional tables with only one hierarchy, due to the limitations of the network flows. Note that the hierarchical variable should be the first variable.

The heuristic is based on the solution of a sequence of shortest-path subproblems that guarantee a feasible pattern of suppressions (i.e.,one that satisfies the protection levels of sensitive cells). Hopefully, this feasible pattern will be close to the optimal one.

The current package is linked with three solvers: CPLEX7.5/8.0 seeILOG(2000)  [pprn]{.smallcaps} see Castro(1996), and an efficient implementation of the bidirectional Dijkstra's algorithm for shortest-paths (that will be denoted as "Dijkstra") see Ahuja(1993). Later releases of [cplex]{.smallcaps} will also work if the interface routines are the same than for version 8.0. The heuristic can use any of the three solvers for the solution of the shortest path subproblems, although Dijkstra is recommended (and the default one) for efficiency reasons. [cplex]{.smallcaps} is needed if alower bound of the optimal solution want to be computed. The auditing phase can be performed with either [cplex]{.smallcaps} or  [pprn]{.smallcaps}.

 [pprn]{.smallcaps} and Dijkstra were implemented at the Dept. of Statistics and Operations Research of the Universitat Politècnica de Catalunya, and are included in NF CSP.  [pprn]{.smallcaps} was originally developed during 1992--1995, but it had to be significantly improved within the CASC project to work with NF CSP. Dijkstra was completely developed in the scope of CASC. The third solver, [cplex]{.smallcaps}, is a commercial tool, and requires purchasing a license. However,  [pprn]{.smallcaps} is a fairly good replacement ---although not so robust--- for the network flows routines of [cplex]{.smallcaps}. Therefore, in principle, there is no need for an external commercial solver, unless lower bounds want to be computed.

Even though two of the three solvers are included in the distribution of NF CSP, this document only describes the features of the heuristic,and from the user's point of view. A detailed description of  [pprn]{.smallcaps} and Dijkstra's solvers can be found in Castro(1996) and Ahuja(1993), respectively.

The current implementation in $\tau$-Argus however only uses the Dijkstra and the [pprn]{.smallcaps} solvers. We have restricted ourselves from commercial solvers here as the network flows give already a very fast solution.

### References on the network solution

1. Ahuja, R.K, Magnanti, T.L., Orlin, J.B., Network Flows, Prentice Hall(1993).
2. Castro, J.,  [pprn]{.smallcaps} 1.0, User's Guide, Technical report DR 94/06 Dept. ofStatistics and Op-erations Research, Universitat Politècnica deCatalunya, Barcelona, Spain, 1994.
3. Castro, J., Network flows heuristics for complementary cellsuppression: an empirical evaluation and extensions, in LNCS 2316,Inference Control in Statistical Databases, J. Domingo-Ferrer (Ed),(2002) 59--73.
4. Castro, J., Nabona, N. An implementation of linear and nonlinearmulticommodity network flows. European Journal of Operational Research92, (1996) 37--53.
5. Cox, L.H., Network models for complementary cell suppression. J. Am.Stat. Assoc. 90, (1995) 1453--1462.
6. ILOG CPLEX, ILOG CPLEX 7.5 Reference Manual Library, ILOG, (2000).
7. Kelly, J.P., Golden, B.L, Assad, A.A., Cell Suppression: disclosureprotection for sensitive tabular data, Networks 22, (1992) 28--55.
8. Castro, J. User's and programmer's manual of the network flowsheuristics package for cell suppression in 2D tables Technical ReportDR 2003-07, Dept. of Statistics and Operations Research, UniversitatPolitècnica de Catalunya, Barcelona, Spain,2003;
9. See[*http://research.cbs.nl/casc/deliv/41D5-NF-Tau-Argus.pdf*](http://research.cbs.nl/casc/deliv/41D5-NF-Tau-Argus.pdf)

