## About the name ARGUS
Somewhat jokingly the name argus can be interpreted as the acronym of'Anti-Re-identification General Utility System'^[^2]^. As a matter offact, the name argus was inspired by a myth of the ancient Greeks. Inthis myth Zeus has a girl friend named Io. Hera, Zeus' wife, did notapprove of this relationship and turned Io into a cow. She let themonster argus guard Io. argus seemed to be particularly well qualifiedfor this job, because it had a hundred eyes that could watch over Io.If it would fall asleep only two of its eyes were closed. That wouldleave plenty of eyes to watch Io. Zeus was eager to find a way to getIo back. He hired Hermes who could make argus fall asleep by theenchanting music on his flute. When Hermes played his flute to argusthis indeed happened: all its eyes closed, one by one. When Hermes hadsucceeded in making argus fall asleep, argus was decapitated. argus'eyes were planted onto a bird's tail - a type of bird that we now knowunder the name of peacock. That explains why a peacock has theseeye-shaped marks on its tail. This also explains the picture on thecover of this manual. It is a copperplate engraving of Gerard deLairesse (1641-1711) depicting the process where the eyes of argus arebeing removed and placed on the peacock's tail.^[^3]^
Like the mythological argus, the software is supposed to guardsomething, in this case data. This is where the similarity between themyth and the package is supposed to end, as we believe that thepackage is a winner and not a loser as the mythological argus is.

