## Controlled rounding[^13]

[^13]: See section 5.4.3 *Rounding* of the SDC Handbook Hundepool et al. (2012).

Controlled rounding is a rounding procedure that, differently from other rounding methods, yields additive rounded tables. That is to say that the rounded values add up to the rounded totals and sub-totals shown in the table. This property not only permits the release of realistic tables but also makes it impossible to reduce the protection by "unpicking" the original values by exploiting the differences in the sums of the rounded values. The Controlled Rounding Procedure (CRP) implemented in $\tau$-Argus also allows the specification hierarchical tables.

Controlled rounding is a SDC method that is most effective for frequency tables. In fact, this method gives adequate protection to small frequencies by creating uncertainty also with respect to zero values (*i.e.* empty cells). The same cannot be said for suppression in the way it is implemented now in $\tau$-Argus.

### Restricted and non-restricted controlled rounding

In Zero-restricted Controlled Rounding the rounded values are chosen leaving unaltered the original values that are already multiples of the rounding base, while rounding the others to one of the adjacent multiples of this base. The modified values are chosen so that the sum of the absolute differences between the original values and the rounded ones is minimized under the additivity constraint. Therefore, some values will be rounded up or down to the most distant multiple of the base in order to satisfy the constraints. In most cases such a solution can be found but in some cases it cannot. The zero-restriction constraint in CRP can be relaxed allowing the values to be rounded to a non adjacent multiple of the base. This relaxation is controlled by allowing a maximum number of *steps*. For example, consider rounding the value $7$ when the base equals $5$. In zero-restricted rounding, the solution can be either $5$ or $10$. If $1$ step is allowed, the solution can be $0, 5, 10$ or $15$. In general, let $z$ be the integer to be rounded in base $b$, then this number can bewritten as
$${z = {\mathit{ub} + r}},$$

where $ub$ is the lower adjacent multiple of $b$ (hence $u$ is the floor value of $z/b$) and $r$ is the remainder. In the zero-restricted solution the rounded value, $a$, can take values:
$$\left\{ \begin{matrix}{{a = \mathit{ub}}\mathit{if}{r = 0};} \\{{a = \left\{ \begin{matrix}\mathit{ub} \\{{({u + 1})}b}\end{matrix} \right.}\mathit{if}{r \neq 0.}}\end{matrix} \right.$$

If $K$ steps are allowed, then $a$, can take values:

$$\left\{ \begin{matrix}{{a = \mathit{\max}}{\{{0,{({u + j})}}\}}b,{j = {- K}},\ldots,K,\mathit{if}{r = 0};} \\{{a = \mathit{\max}}{\{{o,{({u + j})}}\}}b,{j = {- K}},\ldots,{({K + 1})},\mathit{if}{r \neq 0.}}\end{matrix} \right.$$

### Optimal, first feasible and RAPID solutions[^14]

[^14]: For further details see Salazar, Staggermeier and Bycroft (2005 *Controlled rounding implementation*, UN-ECE Worksession on SDC, Geneva)

For a given table there could exist more than one controlled rounded solutions; any of these solutions is a *feasible* solution. The Controlled Rounding Program embedded in $\tau$-Argus determines the *optimal* solution by minimising the sum of the absolute distances of the rounded values from the original ones. Denoting the cell values, including the totals and sub-totals, with $z_{i}$ and the correspondingrounded values with $a$~i~, the function that is minimised is
$${\sum\limits_{i = 1}^{N}{\mid {z_{i} - a_{i}} \mid}},$$

where $N$ is the number of cells in a table (including the marginalones). The optimisation procedure for controlled rounding is a rather complex one (*NP*-complete program), so finding the optimal solution may take a long time for large tables. In fact, the algorithm iteratively builds different rounded tables until it finds the optimal solution. In order to limit the time required to obtain a solution,the algorithm can be stopped when the first feasible solution is found. In many cases, this solution is quite close to the optimal one and it can be found in significantly less time.

The RAPID solution is produced by CRP as an approximated solution when not even a feasible one can be found. This solution is obtained by rounding the internal cells to the closest multiple of the base and then computing the marginal cells by addition. This means that the computed marginal values can be many jumps away from the original value. However, a RAPID solution is produced at each iteration of the search for an optimal one and it will improve (in terms of the loss function) over time. $\tau$-Argus allows to stop CRP after the first RAPID is produced, but this solution is likely to be very far away from the optimal one.

### Protection provided by controlled rounding

The protection provided by controlled rounding can be assessed by considering the uncertainty about the disclosive true values achieved releasing rounded values; that is the existence interval that an intruder can compute for the rounded value. We assume that also the values of the rounding base, $b$, and the number of steps allowed, $K$, are released together with the rounded table. Furthermore, we assume that it is known that the original values are frequencies (hence nonnegative integers).

#### Zero-restricted rounding

Given a rounded value, $a$, an intruder can compute the following existence intervals for the true value, $z$:
$$\begin{matrix}{{z \in {\lbrack{0,{b - 1}}\rbrack}}\mathit{if}{a = 0}} \\{{z \in {\lbrack{{{a - b} + 1,}{{a + b} - 1}}\rbrack}}\mathit{if}{a \neq 0.}}\end{matrix}$$

For example, if the rounding base is $b=5$ and the rounded value is $a=0$, a user can determine that the original value is between $0$ and $4$. If the rounded value is not $0$, then users can determine that thetrue value is between plus or minus 4 units from the published value.

#### K-step rounding

As mentioned before, it is assumed that the number of steps allowed is released together with the rounded table. Let $K$ be the number of steps allowed, then an intruder can compute the following existence intervals for the true value $z$:
$$\begin{matrix}{{z \in {\lbrack{0,{({K + 1})}{b - 1}}\rbrack}}\mathit{if}{a < {({K + 1})}}b} \\{{z \in {\lbrack{{a - {({K + 1})}}{b + 1,}{a + {({K + 1})}}{b - 1}}\rbrack}}\mathit{if}{a \geq {({K + 1})}}\mathit{b.}}\end{matrix}$$

For example, assume that for controlled rounding with $b=5$ and $K=1$, $a=15$, then a user can determine that 
$${z \in {\lbrack{6,24}\rbrack}}.$$

### Choosing the parameters for Controlled Rounding

The parameters that can be chosen for rounding are the rounding base, $b$, and the number of steps allowed. If their value is released,users (including potential intruders) will be able to compute existence intervals for the true values according to the formulae given above. Then, the choice of the parameters' values depends on the protection required for the disclosive values. Of course, the larger the existence interval the greater the protection but also the *damage* caused to the data. The choice of the rounding base, then, should be made by the data protector considering the protection requirements and the damage caused to the data. A discussion on how existence intervals can be related to protection requirements can be found, for example, in Willenborg and de Waal (2001). Below we give some general considerations on the effect of different choices of the rounding base.

Frequencies are disclosive if their values are not larger than a chosen threshold, say $f$. In $\tau$-Argus the minimal rounding base is $b=f$. When this value is chosen, disclosive values can be rounded either to $0$ or to $b$. Hence, an intruder would know that all published zeros are disclosive values, while he or she could not determine if a published value equal to $b$ is a disclosive value or a larger, safe, one. In some cases this protection can be considered insufficient because it is required that the existence interval for values rounded to zero contains at least one safe value. Then the value of $b$ must be chosen to be greater than $f$ or the number of steps allowed must be greater than zero. It must be stressed, however, that the larger the base and the greater the damage inflicted to the data (including safe values). In some cases, data protector may be happy with a base that is less than the minimum frequency threshold. For example, it could be decided that the width of the existence interval must be not less than the minimum frequency. In this case, the base should be chosen to be the minimal integer not smaller than $f/2$. Using a smaller base than the minimum safe frequency can be achieved in $\tau$-Argus by lowering the threshold before computing the table. This "trick" is allowed in rounding because the procedure does not change if the disclosive cells are changed (unlike secondary suppression).

