## Sensitive cells in frequency count tables

In the simplest way of using $\tau$-Argus, sensitive cells in frequency count tables are defined as those cells that contain a frequency that is below a certain threshold value. This threshold value is to be provided by the data protector. This way of identifying unsafe cells in a table is the one that is implemented in the current version of $\tau$-Argus. It should be remarked, however, that this is not always an adequate way to protect a frequency count table.[^7] Yet it is applied a lot. Applying a dominance rule or a $p$% rule is useless in this context. One should think about possible disclosure risks that a frequency count table poses and possible disclosure scenarios in order to simulate the behaviour of an intruder. Such an analysis would probably come up with different insights than using a simple thresholding rule, *e.g.* like the one sketched in the reference just mentioned. We just mention here the risks of group-disclosure; when a(small) group of respondents have all the same score on a certain category. This risk is often also referred to as the problem of $100$%-cells. Further research on this topic is being carried out at Statistics Netherlands.

