## Global recode file
Global recoding is a powerful method to reduce the number of primaryunsafe cells. It reduces the size of the table, but the advantage isalso that the number of primary unsafe cells is reduced. It is aclassical balance to decide how far you should go when applying globalrecodes, but often the resulting table contains much more information,compared to a table with many, but suppressed cells.
For a hierarchical coding scheme $\tau$-Argus allows recoding viacollapsing the tree structure of the hierarchy. But for non-structuredcodelists the global recode must be specified manually
The structure is always: A new code is assigned to a set of old codes.So all the old codes are collapsed into the new code. A set can beeither a list of individual codes, separated by a comma, or aninterval indicated by a lower code, dash upper code. If the upper orlower code is not specified an open interval is assumed.
Examples:
For a variable with the categories 1,...,182 a possible recode isthen:
1: - 49
2: 50 - 99
3: 100 -- 149
4: 150 --
This implies that every code below 49 will be recoded into the newcode 1,all codes between 50 and 99 will be the new code 2 etc.
For a variable with the categories 01 till 10 a possible recode is:
1: 01 , 02
2: 03 , 04
3: 05 -- 07
4: 08 , 09 , 10
An important point is not to forget the colon (:) if it is forgotten,the recode will not work.
Recoding 3: 05,06,07 can be shortened to 3: 05-07.
And the two different schemes can be combined as well
1: 02 - 06, 09
is a valid recode as well.

