## Log file
τ-argus will write a log-file. This describes among others thecommands used during the runs of τ-argus. If gives a log of the use ofτ-argus. Especially for the batch process this file could give someinformation about the progress of the process. Notably is some errorhas occurred, as a batch version cannot inform the user interactively.Below is given a small example. Please note that new information isalways added to this file. So from time to time the user should deletethis file to clean his computer.
By default the logfile is the file taulogbook.txt in thetemp-directory. In the options window the name of the logfile can bechanged for the remainder of the current session and future sessions.
The Temp directory is normally something like
C:\\Users\\*YOURNAME*\\AppData\\Local\\Temp
where yourname is the name of the current user. Of course in specificcircumstances the network administrator might have a chosen differentlocation.
When running in batch-mode it is possible to change the name of thelog-file with a batch command in the batch-file or as the secondparameter on the commandline. See section [4.3.4](#anchor-192)
23-Oct-2014 16:17:27 : Start of TauArgus run
23-Oct-2014 16:17:27 : Version 4.0.1 (beta) build 3
23-Oct-2014 16:17:27 :\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--
23-Oct-2014 16:17:35 : Start of batch procedure; file:D:\\TauJava3\\Datata\\manual.arb
23-Oct-2014 16:17:35 : \<OPENMICRODATA\> \"C:\\ProgramFiles\\TauARGUS\\data\\tau_testW.asc\"
23-Oct-2014 16:17:35 : \<OPENMETADATA\> \"C:\\ProgramFiles\\TauARGUS\\data\\tau_testW.rda\"
23-Oct-2014 16:17:35 : \<SPECIFYTABLE\>\"Size\"\"region\"\|\"var2\"\|\"var3\"\|\"var3\"
23-Oct-2014 16:17:35 : \<SAFETYRULE\> P(20,3)\|FREQ(3,30)\|ZERO(20)
23-Oct-2014 16:17:35 : \<SPECIFYTABLE\>\"Size\"\"Year\"\|\"var2\"\|\"var3\"\|\"var3\"
23-Oct-2014 16:17:35 : \<SAFETYRULE\> NK(3,70)\|FREQ(3,30)\|ZERO(20)
23-Oct-2014 16:17:35 : \<READMICRODATA\>
23-Oct-2014 16:17:35 : Start explore file: C:\\ProgramFiles\\TauARGUS\\data\\tau_testW.asc
23-Oct-2014 16:17:35 : Start computing tables
23-Oct-2014 16:17:36 : Table: Size x Region \| Var2 has been specified
23-Oct-2014 16:17:36 : Table: Size x Year \| Var2 has been specified
23-Oct-2014 16:17:36 : Tables have been computed
23-Oct-2014 16:17:36 : Micro data file read; processing time 1 seconds
23-Oct-2014 16:17:36 : Tables from microdata have been read
23-Oct-2014 16:17:36 : \<SUPPRESS\> GH(1,75)
23-Oct-2014 16:17:36 : Start of the hypercube protection for tableSize x Region \| Var2
23-Oct-2014 16:17:37 : End of hypercube protection. Time used 1seconds
Number of suppressions: 10
23-Oct-2014 16:17:37 : The hypercube procedure has been applied
10 cells have been suppressed
23-Oct-2014 16:17:37 : \<WRITETABLE\>(1,1,AS+,\"D:\\TauJava3\\Datata\\x1.csv\")
23-Oct-2014 16:17:37 : Table: Size x Region \| Var2 has been written
Output file name: D:\\TauJava3\\Datata\\x1.csv
23-Oct-2014 16:17:37 : \<SUPPRESS\> GH(2,75)
23-Oct-2014 16:17:37 : Start of the hypercube protection for tableSize x Year \| Var2
23-Oct-2014 16:17:39 : End of hypercube protection. Time used 1seconds
Number of suppressions: 5
23-Oct-2014 16:17:39 : The hypercube procedure has been applied
5 cells have been suppressed
23-Oct-2014 16:17:39 : \<WRITETABLE\>(2,2,QU+,\"D:\\TauJava3\\Datata\\y11.csv\")
23-Oct-2014 16:17:39 : Table: Size x Year \| Var2 has been written
Output file name: D:\\TauJava3\\Datata\\y11.csv
23-Oct-2014 16:17:39 : \<SUPPRESS\> MOD(1)
23-Oct-2014 16:17:39 : Start of the modular protection for table Sizex Region \| Var2
23-Oct-2014 16:17:39 : End of modular protection. Time used 0 seconds
Number of suppressions: 10
23-Oct-2014 16:17:40 : \<WRITETABLE\>(1,3,AS-,\"D:\\TauJava3\\Datata\\x20.txt\")
23-Oct-2014 16:17:40 : Table: Size x Region \| Var2 has been written
Output file name: D:\\TauJava3\\Datata\\x20.txt
23-Oct-2014 16:17:40 : \<SUPPRESS\> MOD(2)
23-Oct-2014 16:17:40 : Start of the modular protection for table Sizex Year \| Var2
23-Oct-2014 16:17:40 : End of modular protection. Time used 0 seconds
Number of suppressions: 5
23-Oct-2014 16:17:41 : \<WRITETABLE\>(2,4,SE+,\"D:\\TauJava3\\Datata\\y20.tab\")
23-Oct-2014 16:17:41 : Table: Size x Year \| Var2 has been written
Output file name: D:\\TauJava3\\Datata\\y20.tab
23-Oct-2014 16:17:41 : \<SUPPRESS\> OPT(1,5)
23-Oct-2014 16:17:41 : End of Optimal protection. Time used 0 seconds
Number of suppressions: 12
23-Oct-2014 16:17:42 : \<WRITETABLE\>(1,1,AS+,\"D:\\TauJava3\\Datata\\x3.csv\")
23-Oct-2014 16:17:42 : Table: Size x Region \| Var2 has been written
Output file name: D:\\TauJava3\\Datata\\x3.csv
23-Oct-2014 16:17:42 : \<GOINTERACTIVE\>


