## Acknowledgments 
$\tau$-Argus was started as part of the EU 4^th^ framework SDC-project andbecame a mature software tool as part of the CASC project that waspartly sponsored by the EU under contract number IST-2000-25069. Thissupport is highly appreciated. The CASC (Computational Aspects ofStatistical Confidentiality) project is part of the Fifth Framework ofthe European Union. The main part of $\tau$-Argus has been developed atStatistics Netherlands by Aad van de Wetering and Ramya Ramaswamy (whowrote the kernel) and Anco Hundepool (who wrote the interface).However this software would not have been possible without thecontributions of several others, both partners in the CASC-project andoutsiders. Recent extensions of $\tau$-Argus have been made possible duringthe European CENEX-SDC-project (grant agreement25200.2005.001-2005.619), the ESSNet-SDC project (grant agreement25200.2005.003-2007.670.) and the ESSnet SDC harmonisation(61102.2010.004-2010.579).
The Open Source transition was supported by a Eurostat grant(61102.2012.001-2012.102).
The German partners ****Statistisches Bundesamt (Sarah Giessing andDietz Repsilber) have contributed the ****ghmiter**** software, whichoffers a solution for secondary cell suppression based on hypercubes.Peter-Paul de Wolf has built a ****search algorithm based onnon-hierarchical optimal solutions. This algorithm breaks down a largehierarchical table into small non-hierarchical subtables, which arethen individually protected. A team led by JJ Salazar of theUniversity La Laguna Tenerif****e, Spain, has developed theoptimisation routines. Additionally Jordi Castro, UniversitatPolitècnica de Catalunya. Barcelona, has developed a solution based onnetworks. Jordi Castro also developed the CTA solution.****
****The controlled rounding procedure has been developed by JJSala****zar in a project sponsored by ONS. In order to enhance theusability τ-****argus**** now also can handle SPSS-system files. Forusing τ-****argus**** in combination with SAS, several reports havebeen produced during the ESSnet projects. These reports and also theSAS-tools are available from the CASC/ESSNet website.****
****The audit routine was first developed by Karl Luhn of theUniversity of ****Ilmenau and further developed by Destatis.
For solving these optimisation problems, $\tau$-Argus traditionally usescommercial LP-solvers. Traditionally we use Xpress as an LP-solver.This package is kindly made available for users of $\tau$-Argus in aspecial agreement between the $\tau$-Argus-team and FICO, the developers ofXpress. Alternatively $\tau$-Argus can also use the cplex-package. Userscan choose either solver to link to $\tau$-Argus (provided, of course, theypurchase a license for the solver chosen). However users alreadyhaving a licence for one of these packages for other applications canuse their current licence for $\tau$-Argus as well.
Starting with this Open Source version also free and open solver(Soplex) can now be used to solve the optimisation models behind CellSuppression, rounding and CTA.

