## Preface
This is the user\'s manual for $\tau$-Argus version 4.1. $\tau$-Argus is a software tool designed to assist a data protector in producing safe tables. This manual describes the first Open Source version of $\tau$-Argus. After a long history of development at Statistics Netherlands(CBS) as closed software, CBS has decided to convert $\tau$-Argus towards Open Source. This process coincides with the formal retirement of the main developer, Anco Hundepool. With the financial support of Eurostat we have been able to do this transformation and we hope that thefuture of $\tau$-Argus is secured. The main aim of this transition project was to port the current (version 3.5) of $\tau$-Argus to an open environment. So this version 4.1 does not contain many new extensions.The whole user-interface has been rewritten in java, replacing the old Visual Basic version. The aim of this transition is to be in an open environment and also be platform independent. So also a unix versionis possible now.
Nevertheless with respect to the previous release of $\tau$-Argus we have made a few steps forward, and $\tau$-Argus now has facilities to protect tables via Controlled Tabular Adjustment (CTA). These routines for this have been developed by Jordi Castro of the Polytechnic Universityof Catalonia.
We have also added the option to use a free open solver (soplex) in addition to the classical commercial solvers like cplex and Xpress. However we expect that these commercial solvers are still very much needed, when we want to protect large serious tables.
The purpose of $\tau$-Argus is to protect tables against the risk of disclosure, i.e. the accidental or deliberate disclosure of information related to individuals from a statistical table. This is achieved by modifying the table so that it contains less detailed information. $\tau$-Argus allows for several modifications of a table: a table can be redesigned, meaning that rows and columns can be combined; sensitive cells can be suppressed and additional cells to protect these can be found in some optimum way (secondary cell suppression). Also rounding and CTA can be used to protect sensitive tables.
The purpose of the present manual is to give a potential user enough information so that he can understand the general principles on which $\tau$-Argus is based, and also allow him to use the package. So it contains both general background information and detailed program information. For a more in-depth theoretical background we refer to the handbook "[Statistical DisclosureControl](http://eu.wiley.com/WileyCDA/WileyTitle/productCd-1119978157.html)" by Anco Hundepool, Josep Domingo-Ferrer, Luisa Franconi, SarahGiessing, Eric Schulte Nordholt, Keith Spicer and Peter-Paul de Wolf(ISBN: 978-1-119-97815-2, Wiley, 2012).
$\tau$-Argus is one of a twin set of disclosure control packages. For the protection of microdata - $\mu$-Argus - has been developed, which is the twin brother of $\tau$-Argus.^[^1]^ Also $\mu$-Argus has been ported to OpenSource.

